title: Dan Schaffer's Home Page
email: danielhschaffer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dan Schaffer's home page full of random notes and projects.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://danschaffer.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danscha
github_username:  danschaffer
linkedin_username: dan-schaffer-785244
# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: "My Title"
